### ISSUE TITLE
Old version on PyPI

### ISSUE THREAD

**Issue by herm** [vitiral/gpio#4]
The version on PyPI doesn't work because of this bug:
https://github.com/vitiral/gpio/commit/c3be81d1f5fdefccf087137cfee55982964536c7#diff-79acd40d450fc56c31ea38a0a81a961cL154

Please prepare a new version and upload it.

**Comment by vitiral** [comment]
Hey, thanks for the issue. I'll try to take a look at this soon

**Comment by vitiral** [comment]
everything should be pushed to version 0.2.0. Thanks for the bug report
