### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jsantala** [vitiral/gpio#5]
Could you add a license to your library, for example the BSD license? Not having a license makes using the software complicated. :) Thanks a lot!

**Comment by CRImier** [comment]
Hi! Agreed - this seems to be the most low-profile specific-purpose library I found, but not having a license seems to be problematic.

**Comment by vitiral** [comment]
thanks for pinging me. License is MIT

**Comment by CRImier** [comment]
Thanks for solving this so quickly, too! =)
